# 拦截器说明

axios 中的拦截器分为请求拦截器和响应拦截器，其作用是分别在发送请求前和接收响应之前，进行一系列的数据检测或处理，处理之后再继续请求的发送或响应的接收。

<aside>
💡 拦截器就类似一道道关卡，只有在满足条件时才能放行。并且拦截器可以不止一个。

</aside>

# 请求拦截器示例

请求拦截器具有后定义先执行的特性，如果同时定义了多个请求拦截器，则这些拦截器的顺序是最后定义的先执行、倒数第二个第二个执行，以此类推，倒序执行。

```jsx
axios.interceptors.request.use(function (config) {
		console.log("请求拦截器 1 成功");
		return config;    // 此处的 config 是在请求时传入的 axios 请求参数
}, function (error) {
		console.log("请求拦截器 1 失败");
		return Promise.reject(error);
})

axios.interceptors.request.use(function (config) {
		console.log("请求拦截器 2 成功");
		return config;
}, function (error) {
		console.log("请求拦截器 2 失败");
		return Promise.reject(error);
})

axios({
		url: "http://localhost:3000/post",
}).then(
		response => console.log("自定义回调");
)

//#执行结果:
// 请求拦截器 2 成功
// 请求拦截器 1 成功
// 自定义回调
```

# 响应拦截器示例

当多个响应拦截器同时定义时，按定义顺序执行。

```jsx
axios.interceptors.response.use(function (response) {
		console.log("响应拦截器 1 成功");
		return response;    // 此处的 response 是在响应时 axios 的响应体
}, function (error) {
		console.log("响应拦截器 1 失败");
		return Promise.reject(error);
})

axios.interceptors.response.use(function (response) {
		console.log("响应拦截器 2 成功");
		return response;
}, function (error) {
		console.log("响应拦截器 2 失败");
		return Promise.reject(error);
})

axios({
		url: "http://localhost:3000/post",
}).then(
		response => console.log("自定义回调");
)

//#执行结果:
// 响应拦截器 1 成功
// 响应拦截器 2 成功
// 自定义回调
```